spring:
  #redis
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password:

    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000





