spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8

    # druid 配置
    druid:
      # 监控后台的账号密码
      stat-view-servlet:
        login-username: admin
        login-password: admin
      # 初始化大小、最小、最大连接数
      initial-size: 3
      min-idle: 3
      max-active: 10
      # 获取连接等待超超时的时间
      max-wait: 60000
      # 配置 StatFilter
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000


# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.gxc.entity


# Actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: ['*']  # yml 配置文件为：/*

server:
  port: 8080
  servlet:
    context-path: /


